# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64d586bcbe758e4d89e703d472597f1e406f3db0ae5c87a36a1b72386180e13f660e598e5590e69c906453a951492815cc4d5fcd6ca5ccc7a527527ddafd95f8

test:
  secret_key_base: 482df05bf61b2602732966536d6f9ebf9a4439fdb00ef76d2f2f9039ac87afa92160287ea3d5068d6b07f6cddc97ee55272a0632c53407220c4afab34a409bd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
